### ISSUE TITLE
画面遷移後アラートが表示されない。

### ISSUE THREAD

**Issue by HiroshiOshiro** [mshrwtnb/ALRT#7]
画面遷移のあるアプリで、遷移後の画面でALRTを使おうとすると、以下のようなエラーが出てアラートが表示されません。
Demo[26163:424735] Warning: Attempt to present <UIAlertController: 0x7fd9e5044a00> on <Demo.FirstViewController: 0x7fd9e7c07930> whose view is not in the window hierarchy!

FirstViewControllerといのは、demoのプロジェクトでDemoViewControllerに遷移するViewControllerです。

表示するViewControllerがうまく指定できていないと思うのですが、対策はあるでしょうか？
問題が発生するDemoを含んだZipを添付します。
[ALRT-master_edited.zip](https://github.com/mshrwtnb/ALRT/files/2505427/ALRT-master_edited.zip)

**Comment by mshrwtnb** [comment]
再現確認できました。
1.3.1にて、修正しました。
https://github.com/mshrwtnb/ALRT/releases/tag/1.3.1

**Comment by HiroshiOshiro** [comment]
ありがとうございます！助かります！
